import Head from "next/head";
import HeaderComponent from "@/components/header";
import HomeSection from "@/components/HomeSection";
import { ConfigProvider } from "antd";
import AboutSection from "@/components/About";
import FAQSection from "@/components/FAQ";
import ChromeExtenstionSection from "@/components/ChromeExtenstion";
import ContactSection from "@/components/Contact";
import FooterComponent from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Muscle Password - Strong Random Password Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "#53baf9",
            colorLink: "#53baf9",
            // borderRadius: 7,
          },
          components: {
            // Button: {
            //     colorPrimary: 'red',
            //     algorithm: true,
            // },
          },
        }}
      >
        <HeaderComponent />
        <HomeSection />
        <AboutSection />
        <FAQSection />
        <ChromeExtenstionSection />
        <ContactSection />
        <FooterComponent />
      </ConfigProvider>
    </>
  );
}
